#!/bin/bash
#
# Generate C header with embedded cert/key DER bytes.
#
# Usage: ./gen_embedded_certs.sh <cert.pem> <intermediate.pem> <root.pem> <privkey.pem>
#
# If cert files are missing or empty, generates stub zero-length arrays
# so the build still succeeds (use TLS_SELF_SIGNED or TLS_CERT at runtime).
#
# Outputs: embedded_certs.h in the current directory

set -euo pipefail

if [ $# -ne 4 ]; then
    echo "Usage: $0 <cert.pem> <intermediate.pem> <root.pem> <privkey.pem>" >&2
    exit 1
fi

CERT_PEM="$1"
INTERMEDIATE_PEM="$2"
ROOT_PEM="$3"
PRIVKEY_PEM="$4"

OUT="embedded_certs.h"

# Check if all cert files exist and are non-empty
CERTS_AVAILABLE=true
for f in "$CERT_PEM" "$INTERMEDIATE_PEM" "$ROOT_PEM" "$PRIVKEY_PEM"; do
    if [ ! -s "$f" ]; then
        CERTS_AVAILABLE=false
        break
    fi
done

cat > "$OUT" <<'HEADER'
/*
 * Auto-generated embedded certificate/key data.
 * DO NOT COMMIT THIS FILE - it contains TLS private key material.
 * Generated by gen_embedded_certs.sh during Docker build.
 */
#ifndef EMBEDDED_CERTS_H
#define EMBEDDED_CERTS_H

#include <stdint.h>
#include <stddef.h>

HEADER

if [ "$CERTS_AVAILABLE" = true ]; then
    # Convert PEM to DER
    CERT_DER=$(mktemp)
    INTERMEDIATE_DER=$(mktemp)
    ROOT_DER=$(mktemp)
    PRIVKEY_DER=$(mktemp)
    trap "rm -f $CERT_DER $INTERMEDIATE_DER $ROOT_DER $PRIVKEY_DER" EXIT

    openssl x509 -in "$CERT_PEM" -outform DER -out "$CERT_DER"
    openssl x509 -in "$INTERMEDIATE_PEM" -outform DER -out "$INTERMEDIATE_DER"
    openssl x509 -in "$ROOT_PEM" -outform DER -out "$ROOT_DER"
    openssl rsa -in "$PRIVKEY_PEM" -outform DER -out "$PRIVKEY_DER" 2>/dev/null

    der_to_c_array() {
        local file="$1"
        local name="$2"
        local size
        size=$(wc -c < "$file" | tr -d ' ')

        echo "static const uint8_t ${name}[] = {"
        xxd -i < "$file" | sed 's/^/    /'
        echo "};"
        echo "static const size_t ${name}_LEN = ${size};"
        echo ""
    }

    der_to_c_array "$CERT_DER" "EMBEDDED_CERT" >> "$OUT"
    der_to_c_array "$INTERMEDIATE_DER" "EMBEDDED_INTERMEDIATE" >> "$OUT"
    der_to_c_array "$ROOT_DER" "EMBEDDED_ROOT" >> "$OUT"
    der_to_c_array "$PRIVKEY_DER" "EMBEDDED_PRIVKEY" >> "$OUT"

    echo "Generated $OUT (cert=$(wc -c < "$CERT_DER" | tr -d ' ')B, intermediate=$(wc -c < "$INTERMEDIATE_DER" | tr -d ' ')B, root=$(wc -c < "$ROOT_DER" | tr -d ' ')B, key=$(wc -c < "$PRIVKEY_DER" | tr -d ' ')B)"
else
    echo "WARNING: Cert files missing or empty - generating stub embedded_certs.h" >&2

    cat >> "$OUT" <<'STUB'
/* No certs were provided at build time. Use TLS_SELF_SIGNED=true or TLS_CERT/TLS_KEY at runtime. */
static const uint8_t EMBEDDED_CERT[] = {0};
static const size_t EMBEDDED_CERT_LEN = 0;

static const uint8_t EMBEDDED_INTERMEDIATE[] = {0};
static const size_t EMBEDDED_INTERMEDIATE_LEN = 0;

static const uint8_t EMBEDDED_ROOT[] = {0};
static const size_t EMBEDDED_ROOT_LEN = 0;

static const uint8_t EMBEDDED_PRIVKEY[] = {0};
static const size_t EMBEDDED_PRIVKEY_LEN = 0;

STUB

    echo "Generated stub $OUT (no certs embedded)"
fi

echo "#endif /* EMBEDDED_CERTS_H */" >> "$OUT"
